### ISSUE TITLE
Поле игры: как хранить?

### ISSUE THREAD

**Issue by stden** [levelp/TicTacToe#1]

**Comment by stden** [comment]
ffdd274ecdee3e3e66d367a7d083bcbaba33c77b - поле уже хранится

**Comment by AleksSPb** [comment]
Денис, Поправляйтесь!

2015-05-28 21:31 GMT+03:00 Denis Stepulenok notifications@github.com:

> ffdd274
> https://github.com/levelp/TicTacToe/commit/ffdd274ecdee3e3e66d367a7d083bcbaba33c77b
> - поле уже хранится
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/levelp/TicTacToe/issues/1#issuecomment-106552733.

## 

Всего наилучшего, Пархоменко Александр
